[config]
tenant_id = b2db58a7-befc-4497-9c9e-76a78ba230b0
# You should pass the client id and secret through
# the SLASHDB_CLIENT_ID and SLASHDB_CLIENT_SECRET
# environment variables
#client_id = dc332551-6eb4-47ab-b687-9f44dafde4bd
#client_secret = xDG7C~Fgvxug8g2Gx_gun2VcXe6gtCeMZ~G_gxAz
slashdb_idp_id = entra-id
slashdb_url = http://slashdb.internal
