[config]
keycloak_url = http://keycloak.internal
realm_name = my-realm
client_id = slashdb
# You should pass the username and password through
# the SLASHDB_KEYCLOAK_USERNAME and SLASHDB_KEYCLOAK_PASSWORD
# environment variables
#username = user@example.com
#password = FooBar1235
slashdb_idp_id = keycloak
slashdb_url = http://slashdb.internal
