[config]
service_account_info_file = ./sa_info.json
# You should pass the client id and secret through
# the SLASHDB_CLIENT_ID and SLASHDB_CLIENT_SECRET
# environment variables
#client_id = 12345678912-5S7mpZuejBq2542HH62Iqw3kdtWg7bOQ.apps.googleusercontent.com
#client_secret = NJSFJW-aH4QHNTr6rnXsd9ORmvW-CUVDopf
slashdb_idp_id = google
slashdb_url = http://slashdb.internal
