[config]
#client_id = dc332551-6eb4-47ab-b687-9f44dafde4bd
#username = username.example
#password = username.password
#slashdb_idp_id = okta
#slashdb_url = http://slashdb.internal
#token_url = https://example.okta.com/oauth2/v1/token
